export const IMG_PATHS = {
  HEADER_LOGO: './images/1p_logo.png',
  INTRO_BACKGROUND: './images/1p_bg.png',
  INTRO_KIDS: './images/1p_kids.png',
  INTRO_STAR: './images/1p_star.png',
  INTRO_LINE: './images/1p_line.png',
  BANNER_LOGO: '/images/2p_logo-animation.gif',
  LIVE_BACKGROUND: './images/3p_bg.png',
  LIVE_PAD: '/images/3p_pad.png',
  LIVE_VIDEO: './images/3p_live-video.mp4',
  ACCESS_PAD: '/images/5p_pad.png',
  ACCESS_PHONE: '/images/5p_phone.png',
  DIARY_PHONE: './images/6p_phone.png',
  FEATURE_FIRST: '/images/8p_first.png',
  FEATURE_SECOND: '/images/8p_second.png',
  FEATURE_THIRD: '/images/8p_third.png',
};
